train:
  learning_rate: 0.0001
  weight_decay: 0.0001

defaults:
  - engine: classifier
  - network: classifier
  - network/feature_extractor: resnet18
  - data: cnn_mpmt_postveto_nomichel
  - data/dataset: cnn_mpmt
